### ISSUE TITLE
Script does not support mysql character UTF-8?

### ISSUE THREAD

**Issue by abcfy2** [ukautz/mantis2redmine#7]
when I use this script, it doesn't works.

The command line like this:
 *** Stati ***

Mantis: Status
  new                  :  10
  feedback             :  20
  acknowledged         :  30
  confirmed            :  40
  assigned             :  50
  resolved             :  80
  closed               :  90

Redmine: Status
  ??                   :   1
  ???                  :   2
  ???                  :   3
  ??                   :   4
  ???                  :   5
  ???                  :   6

Status translation
    Mantis               ->     Redmine             
 10:new                  ->   1:??                  
 20:feedback             ->   4:??                  
 30:acknowledged         ->   1:??                  
 40:confirmed            ->   1:??                  
 50:assigned             ->   2:???                 
 80:resolved             ->   3:???                 
 90:closed               ->   3:???  

the data in mysql has Chinese characters and the "??" are all Chinese.

mysql status:
--------------
mysql  Ver 14.14 Distrib 5.5.32, for debian-linux-gnu (x86_64) using readline 6.2

Connection id:		1223
Current database:	
Current user:		root@localhost
SSL:			Not in use
Current pager:		stdout
Using outfile:		''
Using delimiter:	;
Server version:		5.5.32-0ubuntu0.12.04.1 (Ubuntu)
Protocol version:	10
Connection:		Localhost via UNIX socket
Server characterset:	utf8
Db     characterset:	utf8
Client characterset:	utf8
Conn.  characterset:	utf8
UNIX socket:		/var/run/mysqld/mysqld.sock
Uptime:			4 hours 10 min 32 sec

Threads: 12  Questions: 346345  Slow queries: 0  Opens: 4690  Flush tables: 1  Open tables: 324  Queries per second avg: 23.040
--------------

**Comment by prusa** [comment]
This should be fixed by Obones with his pull request #10
